### ISSUE TITLE
Operator == false is working, but != true is not

### ISSUE THREAD

**Issue by marcauberer** [compose-generator/ccom#43]
Randomly stumbled over this bug while testing:

For example: `someIdentifier == false` returns true, but the inverse operation `someIdentifier != true` returns false.

The problem might be the evaluation of comparison statements in the interpreter.

**Comment by Splines** [comment]
is this fixed with #41 ? e.g. this seems to work now:

https://github.com/compose-generator/ccom/blob/58d899272f892c5abb3b43fe95dee6ccef4efa77/compiler/cpp/src/interpreter/Interpreter.cpp#L141

**Comment by marcauberer** [comment]
No, the bug is still there. My suggestion is, that the bug occurs not in die Interpreter and rather before, because I already checked the values of `leftValue`, `rightValue` and `op` in the `evalutateCondition()` method in the interpreter and those values are already wrong.

**Comment by marcauberer** [comment]
Found the reason for the bug really fast: The problem was that the lexer did not fill any of `TOK_TRUE` and `TOK_FALSE` with values, but the parser checked for value `true` of a boolean token. I fixed it now by checking the token type instead of the value, which is rather simple and even more performant.
